name: hello-word-docker

inputs: 
  who-to-greet:
    description: Who to greet?
    required: true
    default: World

outputs:
  time: 
    description: current time

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}