name: GitHub Actions Demo

on: 
  push:
    branches: main
    paths-ignore: [.github/**]
  pull_request_target:
    branches: main
  schedule: 
    - cron: '15 16 * * SUN'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment
        description: Target env

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
      - uses: actions/checkout@v4.1.1
      - run: git branch
      - run: git ls-files

  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'wokflow_dispatch'
    environment:
      name: Test
    steps:
      - run: echo "Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'wokflow_dispatch'
    environment: 
      name: Load-Test
    steps:
      - run: echo "Testing..."
      - run: sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: inputs.environment == 'Production'
    environment: 
      name: Production
      url: https://writeabout.net
    steps:
      - run: |
          echo "Deploying 1..."
          sleep 10
      - run: |
          echo "Deploying 2..."
          sleep 10
      - run: |
          echo "Deploying 3..."
          sleep 10
      - run: |
          echo "Deploying 4..."
          sleep 10
      - run: |
          echo "Deploying 5..."
          sleep 10
    
