name: CI for action

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [hello-world-docker-action/**]
    
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'Tomek'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"